In [1]:
import getpass
from glob import glob
import os
from tqdm import tqdm

import pandas as pd
import plotly.express as px
from scipy.stats import spearmanr, pearsonr
from sklearn.cross_decomposition import PLSRegression

In [2]:
root_dir = os.path.join("/home/", getpass.getuser(), "bio_share/", "stegg_results/")
ensemble_dirs = glob(os.path.join(root_dir, "stcrdab/*"))
pdb_ids = [x.split("/")[-2 if x.endswith("/") else -1] for x in ensemble_dirs]

energy_terms = list()
geo_terms = list()
feature_dfs = list()
for (ensemble_dir, pdb_id) in zip(ensemble_dirs, pdb_ids):
    energy_term_df = pd.read_csv(os.path.join(ensemble_dir, "energy_terms.csv"))
    energy_term_df.set_index(pdb_id + energy_term_df["Unnamed: 0"].str[:-4], inplace=True)
    energy_term_df.drop("Unnamed: 0", axis=1, inplace=True)
    energy_terms = energy_term_df.columns
    geo_df = pd.read_csv(os.path.join(ensemble_dir, "geo.csv"))
    geo_df.set_index(pdb_id + geo_df.pdb_name, inplace=True)
    geo_df.drop("pdb_name", axis=1, inplace=True)
    geo_terms = geo_df.columns
    feature_df = pd.concat([energy_term_df, geo_df], axis=1)
    feature_dfs.append(feature_df)

feature_df = pd.concat(feature_dfs)
feature_df.drop_duplicates(inplace=True)
feature_df.sort_index()
feature_df

,fa_atr,fa_rep,fa_sol,fa_intra_rep,fa_intra_sol_xover4,lk_ball_wtd,fa_elec,pro_close,hbond_sr_bb,hbond_lr_bb,...,angle_112,angle_113,angle_114,angle_115,angle_116,angle_117,angle_118,angle_119,angle_120,angle_121
8EO8_complex_143_roi,-2320.055460,1234.696175,1568.605922,973.118948,78.295307,-7.015822,-751.620886,4.813585,-68.322799,-138.920493,...,1.739632,1.349921,1.196387,1.017621,1.906606,2.472614,1.945206,1.570796,1.570796,0.0
8EO8_complex_147_roi,-2337.947409,1217.370873,1591.203020,984.388912,79.343606,-6.518410,-783.002980,5.064202,-73.194939,-143.719000,...,0.574461,2.135342,1.062468,1.408624,1.076621,2.616798,2.079125,1.570796,1.570796,0.0
8EO8_complex_110_roi,-2332.429734,1304.146641,1602.097439,956.956673,79.938554,-9.043703,-788.552424,5.153323,-69.857440,-138.736355,...,1.132642,1.573592,0.422762,1.629114,0.698582,0.875666,2.718831,1.570796,1.570796,0.0
8EO8_complex_181_roi,-2358.158488,1229.246572,1623.073202,1002.821463,82.125862,-0.196130,-799.632434,4.684932,-70.174664,-148.259155,...,2.262048,0.909064,1.749895,0.505602,1.908951,1.931443,1.391697,1.570796,1.570796,0.0
8EO8_complex_5_roi,-2429.327773,1183.660641,1650.352612,980.637605,80.185683,-2.242251,-822.271981,4.200500,-75.166739,-140.880742,...,1.412595,0.883383,0.793179,1.392724,2.001447,0.470674,2.348414,1.570796,1.570796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6VRM_complex_2_roi,-2442.170327,1626.268022,1637.324889,1030.991801,82.692525,-3.268770,-777.324973,5.406503,-75.650354,-139.304269,...,1.671083,1.721936,1.483983,0.674832,1.414607,2.220677,1.657610,1.570796,1.570796,0.0
6VRM_complex_49_roi,-2393.877722,1474.000488,1625.137759,1037.944011,82.969044,-2.552209,-792.489123,4.597599,-75.295301,-142.449388,...,1.982045,1.534371,1.022681,1.087160,1.938673,0.628395,2.118912,1.570796,1.570796,0.0
6VRM_complex_60_roi,-2430.830083,1343.502624,1639.858301,1015.701515,82.921730,-0.317898,-806.612039,5.199202,-75.788127,-142.012471,...,1.679547,1.969435,1.131697,0.927688,1.137782,2.320470,2.009896,1.570796,1.570796,0.0
6VRM_complex_61_roi,-2388.332963,2718.255656,1490.431770,1231.005285,79.105476,-32.104593,-604.221189,24.115663,-72.134342,-147.196862,...,2.044934,1.485108,1.169088,0.938576,1.377975,2.471280,1.972504,1.570796,1.570796,0.0
6VRM_complex_78_roi,-2379.220700,1390.280775,1618.996458,1015.719889,85.897697,-7.973271,-782.036012,5.290551,-72.770270,-142.129459,...,2.395320,1.039269,1.189592,0.843541,1.871397,0.815075,1.952001,1.570796,1.570796,0.0

In [3]:
score_df = pd.read_csv("stcrdab_scores_filtered.csv", index_col=0)
score_df

,pdb_id,DockQ,F1,iRMSD,LRMSD,fnat,nat_correct,nat_total,fnonnat,nonnat_count,model_total,clashes,len1,len2
1AO7_complex_100_roi,1AO7,0.486835,0.444444,2.763904,3.993340,0.413793,12,29,0.520000,13,25,0,223,9
1AO7_complex_101_roi,1AO7,0.343916,0.406250,4.034967,9.171524,0.448276,13,29,0.628571,22,35,0,223,9
1AO7_complex_102_roi,1AO7,0.336972,0.320000,4.525404,6.429585,0.275862,8,29,0.619048,13,21,0,223,9
1AO7_complex_103_roi,1AO7,0.566692,0.592593,2.071850,4.190820,0.551724,16,29,0.360000,9,25,0,223,9
1AO7_complex_104_roi,1AO7,0.381042,0.392857,4.343991,6.137761,0.379310,11,29,0.592593,16,27,0,223,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8YE4_complex_96_roi,8YE4,0.199169,0.050000,4.276842,9.540469,0.045455,1,22,0.944444,17,18,0,221,9
8YE4_complex_97_roi,8YE4,0.290311,0.255319,4.007089,8.930815,0.272727,6,22,0.760000,19,25,0,221,9
8YE4_complex_98_roi,8YE4,0.130761,0.157895,6.957770,16.411849,0.136364,3,22,0.812500,13,16,0,221,9
8YE4_complex_99_roi,8YE4,0.123808,0.142857,8.743062,16.663863,0.136364,3,22,0.850000,17,20,0,221,9
8YE4_complex_9_roi,8YE4,0.091863,0.040000,7.638807,17.380767,0.045455,1,22,0.964286,27,28,0,221,9

In [4]:
# there is one extra (unscored) model in 8NE8
feature_df = feature_df.loc[score_df.index]
feature_df

,fa_atr,fa_rep,fa_sol,fa_intra_rep,fa_intra_sol_xover4,lk_ball_wtd,fa_elec,pro_close,hbond_sr_bb,hbond_lr_bb,...,angle_112,angle_113,angle_114,angle_115,angle_116,angle_117,angle_118,angle_119,angle_120,angle_121
1AO7_complex_100_roi,-2356.978448,1357.951859,1579.891104,970.809611,80.520478,-0.476014,-779.048339,4.353579,-68.511621,-149.095281,...,1.104976,1.985928,1.347024,0.831967,1.789519,0.785978,1.794569,1.570796,1.570796,0.0
1AO7_complex_101_roi,-2348.663700,1317.592449,1573.370711,968.433347,78.792091,-3.951768,-752.156650,5.449702,-67.241339,-143.195634,...,2.073655,0.781193,1.392572,2.623179,1.385138,1.092986,1.749021,1.570796,1.570796,0.0
1AO7_complex_102_roi,-2320.804264,1377.532592,1576.326098,973.319917,80.390487,-0.308010,-772.169619,7.450865,-72.889402,-145.139947,...,1.473666,1.893861,1.290271,0.655143,2.029332,1.138813,1.851321,1.570796,1.570796,0.0
1AO7_complex_103_roi,-2357.738878,1138.079080,1576.689533,905.475965,74.861519,1.238637,-783.517510,6.698069,-66.505371,-151.320528,...,1.334633,2.114493,1.450502,0.772255,1.636407,0.802842,1.691090,1.570796,1.570796,0.0
1AO7_complex_104_roi,-2294.067802,1222.838816,1549.443173,990.727833,79.718962,-7.943969,-759.782020,4.990235,-72.480736,-138.483272,...,1.494236,2.227185,1.382523,0.710845,1.678234,0.871600,1.759070,1.570796,1.570796,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8YE4_complex_96_roi,-2316.242725,1182.359735,1564.471709,1482.574457,81.664798,-4.859296,-758.375057,3.255442,-78.274772,-135.773768,...,0.405292,1.971266,1.552475,0.704806,1.522250,2.273216,1.589118,1.570796,1.570796,0.0
8YE4_complex_97_roi,-2321.771240,1489.747952,1577.282365,1515.148470,84.059079,-2.855697,-760.975376,4.326770,-78.114526,-135.498060,...,0.488056,2.002951,1.527063,0.753937,1.495520,2.319065,1.614530,1.570796,1.570796,0.0
8YE4_complex_98_roi,-2322.922003,1257.006709,1570.692046,952.784107,85.710909,-6.110923,-760.175555,4.093468,-73.555418,-143.817427,...,1.685171,1.709010,1.329389,0.827512,1.229452,2.285967,1.812204,1.570796,1.570796,0.0
8YE4_complex_99_roi,-2294.990194,1361.337270,1555.687776,946.197640,83.607719,-7.707630,-744.483963,3.754043,-72.572445,-137.806695,...,2.618823,1.260740,1.431961,1.060926,1.405230,2.600422,1.709632,1.570796,1.570796,0.0
8YE4_complex_9_roi,-2338.500255,1306.585872,1591.853674,939.932423,82.507883,-2.307733,-776.268305,3.759828,-76.590814,-138.706742,...,1.735640,2.509807,1.070348,1.172668,0.984820,2.400121,2.071245,1.570796,1.570796,0.0

In [5]:
X = feature_df.values
y = score_df.DockQ.values

pls = PLSRegression(n_components=2)
pls.fit(X, y)

y_hat = pls.predict(X)
px.scatter(x=y, y=y_hat).show()
print(spearmanr(y, y_hat))
print(pearsonr(y, y_hat))

SignificanceResult(statistic=0.7670899001734434, pvalue=0.0)
PearsonRResult(statistic=0.7273657925974372, pvalue=0.0)

In [6]:
result_df = score_df.copy()
result_df["dockq_hat"] = y_hat
result_df

,pdb_id,DockQ,F1,iRMSD,LRMSD,fnat,nat_correct,nat_total,fnonnat,nonnat_count,model_total,clashes,len1,len2,dockq_hat
1AO7_complex_100_roi,1AO7,0.486835,0.444444,2.763904,3.993340,0.413793,12,29,0.520000,13,25,0,223,9,0.338181
1AO7_complex_101_roi,1AO7,0.343916,0.406250,4.034967,9.171524,0.448276,13,29,0.628571,22,35,0,223,9,0.245122
1AO7_complex_102_roi,1AO7,0.336972,0.320000,4.525404,6.429585,0.275862,8,29,0.619048,13,21,0,223,9,0.312492
1AO7_complex_103_roi,1AO7,0.566692,0.592593,2.071850,4.190820,0.551724,16,29,0.360000,9,25,0,223,9,0.361274
1AO7_complex_104_roi,1AO7,0.381042,0.392857,4.343991,6.137761,0.379310,11,29,0.592593,16,27,0,223,9,0.323472
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8YE4_complex_96_roi,8YE4,0.199169,0.050000,4.276842,9.540469,0.045455,1,22,0.944444,17,18,0,221,9,0.276376
8YE4_complex_97_roi,8YE4,0.290311,0.255319,4.007089,8.930815,0.272727,6,22,0.760000,19,25,0,221,9,0.294538
8YE4_complex_98_roi,8YE4,0.130761,0.157895,6.957770,16.411849,0.136364,3,22,0.812500,13,16,0,221,9,0.160847
8YE4_complex_99_roi,8YE4,0.123808,0.142857,8.743062,16.663863,0.136364,3,22,0.850000,17,20,0,221,9,0.142521
8YE4_complex_9_roi,8YE4,0.091863,0.040000,7.638807,17.380767,0.045455,1,22,0.964286,27,28,0,221,9,0.195398

In [7]:
best_models = result_df.loc[result_df.groupby("pdb_id")["dockq_hat"].idxmax()]
best_models

,pdb_id,DockQ,F1,iRMSD,LRMSD,fnat,nat_correct,nat_total,fnonnat,nonnat_count,model_total,clashes,len1,len2,dockq_hat
1AO7_complex_54_roi,1AO7,0.390023,0.433333,3.743588,7.182035,0.448276,13,29,0.580645,18,31,0,223,9,0.362191
1G6R_complex_119_roi,1G6R,0.424561,0.514286,2.777763,7.319187,0.473684,9,19,0.437500,7,16,0,221,8,0.406212
1LP9_complex_6_roi,1LP9,0.885688,0.800000,0.918654,1.407539,0.956522,22,23,0.312500,10,32,0,226,9,0.417789
1MI5_complex_60_roi,1MI5,0.337607,0.166667,2.794662,7.097946,0.200000,3,15,0.857143,18,21,0,221,9,0.397184
1MWA_complex_106_roi,1MWA,0.453803,0.421053,2.688215,5.248375,0.400000,8,20,0.555556,10,18,0,221,8,0.393503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8I5D_complex_108_roi,8I5D,0.417590,0.342857,2.805472,7.399057,0.461538,6,13,0.727273,16,22,0,213,9,0.411681
8SHI_complex_48_roi,8SHI,0.291354,0.142857,3.832835,7.543222,0.181818,2,11,0.882353,15,17,0,218,9,0.394784
8WTE_complex_33_roi,8WTE,0.237764,0.060606,5.087760,7.589660,0.076923,1,13,0.950000,19,20,0,222,9,0.403725
8WUL_complex_44_roi,8WUL,0.482327,0.333333,3.266837,5.703664,0.583333,7,12,0.766667,23,30,0,223,9,0.429731
8YE4_complex_34_roi,8YE4,0.387784,0.342857,2.599860,6.362792,0.272727,6,22,0.538462,7,13,0,221,9,0.421009

In [8]:
thresholds = [0.00, 0.23, 0.49, 0.80, 1.00]
for i in range(len(thresholds) - 1):
    print(len(best_models[(best_models.DockQ >= thresholds[i]) & (best_models.DockQ < thresholds[i + 1])]) / len(best_models))

0.04522613065326633
0.4371859296482412
0.4221105527638191
0.09547738693467336

In [9]:
result_df = None
spearmans = dict()

for pdb_id in tqdm(score_df.pdb_id.unique()):

    X_train = feature_df[~feature_df.index.str.startswith(pdb_id)].values
    y_train = score_df[score_df.pdb_id != pdb_id].DockQ.values

    pls = PLSRegression(n_components=2)
    pls.fit(X_train, y_train)

    X_test = feature_df[feature_df.index.str.startswith(pdb_id)].values
    score_test_df = score_df[score_df.pdb_id == pdb_id]
    y_test = score_test_df.DockQ.values

    y_hat = pls.predict(X_test)
    score_test_df["dockq_hat"] = y_hat

    if result_df is None:
        result_df = score_test_df
    else:
        result_df = pd.concat([result_df, score_test_df])

    spearmans[pdb_id] = spearmanr(y_test, y_hat)[0]

spearman_df = pd.Series(spearmans)

  0%|          | 0/199 [00:00<?, ?it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  1%|          | 1/199 [00:00<00:23,  8.32it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  1%|          | 2/199 [00:00<00:23,  8.52it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  2%|▏         | 3/199 [00:00<00:23,  8.35it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  2%|▏         | 4/199 [00:00<00:23,  8.45it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  3%|▎         | 5/199 [00:00<00:22,  8.54it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  3%|▎         | 6/199 [00:00<00:23,  8.28it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  4%|▎         | 7/199 [00:00<00:22,  8.41it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  4%|▍         | 8/199 [00:00<00:24,  7.78it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  5%|▍         | 9/199 [00:01<00:23,  8.02it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  5%|▌         | 10/199 [00:01<00:23,  8.21it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  6%|▌         | 11/199 [00:01<00:22,  8.37it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  6%|▌         | 12/199 [00:01<00:22,  8.46it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  7%|▋         | 13/199 [00:01<00:21,  8.55it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  7%|▋         | 14/199 [00:01<00:21,  8.64it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  8%|▊         | 15/199 [00:01<00:21,  8.59it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  8%|▊         | 16/199 [00:01<00:21,  8.60it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  9%|▊         | 17/199 [00:02<00:21,  8.63it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  9%|▉         | 18/199 [00:02<00:20,  8.64it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 10%|▉         | 19/199 [00:02<00:20,  8.67it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 10%|█         | 20/199 [00:02<00:20,  8.71it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 11%|█         | 21/199 [00:02<00:20,  8.70it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 11%|█         | 22/199 [00:02<00:20,  8.69it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 12%|█▏        | 23/199 [00:02<00:20,  8.69it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 12%|█▏        | 24/199 [00:02<00:19,  8.78it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 13%|█▎        | 25/199 [00:02<00:19,  8.75it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 13%|█▎        | 26/199 [00:03<00:19,  8.73it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 14%|█▎        | 27/199 [00:03<00:19,  8.73it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 14%|█▍        | 28/199 [00:03<00:19,  8.75it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 15%|█▍        | 29/199 [00:03<00:19,  8.75it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 15%|█▌        | 30/199 [00:03<00:19,  8.77it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 16%|█▌        | 31/199 [00:03<00:19,  8.74it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 16%|█▌        | 32/199 [00:03<00:19,  8.73it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 17%|█▋        | 33/199 [00:03<00:19,  8.71it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 17%|█▋        | 34/199 [00:03<00:18,  8.71it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 18%|█▊        | 35/199 [00:04<00:19,  8.44it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 18%|█▊        | 36/199 [00:04<00:19,  8.53it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 19%|█▊        | 37/199 [00:04<00:18,  8.56it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 19%|█▉        | 38/199 [00:04<00:18,  8.56it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 20%|█▉        | 39/199 [00:04<00:18,  8.57it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 20%|██        | 40/199 [00:04<00:18,  8.60it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 21%|██        | 41/199 [00:04<00:18,  8.67it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 21%|██        | 42/199 [00:04<00:18,  8.72it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 22%|██▏       | 43/199 [00:05<00:18,  8.66it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 22%|██▏       | 44/199 [00:05<00:17,  8.64it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 23%|██▎       | 45/199 [00:05<00:17,  8.66it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 23%|██▎       | 46/199 [00:05<00:17,  8.67it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 24%|██▎       | 47/199 [00:05<00:17,  8.69it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 24%|██▍       | 48/199 [00:05<00:17,  8.68it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 25%|██▍       | 49/199 [00:05<00:17,  8.46it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 25%|██▌       | 50/199 [00:05<00:17,  8.55it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 26%|██▌       | 51/199 [00:05<00:17,  8.56it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

 26%|██▌       | 52/199 [00:06<00:17,  8.60it/s]/tmp/ipykernel_1276063/423226277.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


In [10]:
spearman_df.sort_values()

3TF7   -0.407707
4JRY   -0.232299
8GOM   -0.172461
5SWS   -0.100051
7JWI   -0.071949
          ...
2AK4    0.909936
3VXR    0.916490
1LP9    0.917839
2UWE    0.921333
3MV9    0.936292
Length: 199, dtype: float64

In [11]:
result_df

,pdb_id,DockQ,F1,iRMSD,LRMSD,fnat,nat_correct,nat_total,fnonnat,nonnat_count,model_total,clashes,len1,len2,dockq_hat
1AO7_complex_100_roi,1AO7,0.486835,0.444444,2.763904,3.993340,0.413793,12,29,0.520000,13,25,0,223,9,5422.808708
1AO7_complex_101_roi,1AO7,0.343916,0.406250,4.034967,9.171524,0.448276,13,29,0.628571,22,35,0,223,9,5422.704453
1AO7_complex_102_roi,1AO7,0.336972,0.320000,4.525404,6.429585,0.275862,8,29,0.619048,13,21,0,223,9,5422.786765
1AO7_complex_103_roi,1AO7,0.566692,0.592593,2.071850,4.190820,0.551724,16,29,0.360000,9,25,0,223,9,5422.817122
1AO7_complex_104_roi,1AO7,0.381042,0.392857,4.343991,6.137761,0.379310,11,29,0.592593,16,27,0,223,9,5422.807224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8YE4_complex_96_roi,8YE4,0.199169,0.050000,4.276842,9.540469,0.045455,1,22,0.944444,17,18,0,221,9,0.276525
8YE4_complex_97_roi,8YE4,0.290311,0.255319,4.007089,8.930815,0.272727,6,22,0.760000,19,25,0,221,9,0.294668
8YE4_complex_98_roi,8YE4,0.130761,0.157895,6.957770,16.411849,0.136364,3,22,0.812500,13,16,0,221,9,0.161234
8YE4_complex_99_roi,8YE4,0.123808,0.142857,8.743062,16.663863,0.136364,3,22,0.850000,17,20,0,221,9,0.142630
8YE4_complex_9_roi,8YE4,0.091863,0.040000,7.638807,17.380767,0.045455,1,22,0.964286,27,28,0,221,9,0.196010

In [12]:
best_models = result_df.loc[result_df.groupby("pdb_id")["dockq_hat"].idxmax()]
best_models

,pdb_id,DockQ,F1,iRMSD,LRMSD,fnat,nat_correct,nat_total,fnonnat,nonnat_count,model_total,clashes,len1,len2,dockq_hat
1AO7_complex_129_roi,1AO7,0.373649,0.440000,3.613564,7.017795,0.379310,11,29,0.476190,10,21,0,223,9,5422.831177
1G6R_complex_119_roi,1G6R,0.424561,0.514286,2.777763,7.319187,0.473684,9,19,0.437500,7,16,0,221,8,0.403103
1LP9_complex_6_roi,1LP9,0.885688,0.800000,0.918654,1.407539,0.956522,22,23,0.312500,10,32,0,226,9,0.416310
1MI5_complex_60_roi,1MI5,0.337607,0.166667,2.794662,7.097946,0.200000,3,15,0.857143,18,21,0,221,9,0.396270
1MWA_complex_106_roi,1MWA,0.453803,0.421053,2.688215,5.248375,0.400000,8,20,0.555556,10,18,0,221,8,0.392270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8I5D_complex_108_roi,8I5D,0.417590,0.342857,2.805472,7.399057,0.461538,6,13,0.727273,16,22,0,213,9,0.410564
8SHI_complex_48_roi,8SHI,0.291354,0.142857,3.832835,7.543222,0.181818,2,11,0.882353,15,17,0,218,9,0.395019
8WTE_complex_33_roi,8WTE,0.237764,0.060606,5.087760,7.589660,0.076923,1,13,0.950000,19,20,0,222,9,0.403821
8WUL_complex_44_roi,8WUL,0.482327,0.333333,3.266837,5.703664,0.583333,7,12,0.766667,23,30,0,223,9,0.430762
8YE4_complex_34_roi,8YE4,0.387784,0.342857,2.599860,6.362792,0.272727,6,22,0.538462,7,13,0,221,9,0.421234

In [13]:
thresholds = [0.00, 0.23, 0.49, 0.80, 1.00]
for i in range(len(thresholds) - 1):
    print(len(best_models[(best_models.DockQ >= thresholds[i]) & (best_models.DockQ < thresholds[i + 1])]) / len(best_models))

0.05025125628140704
0.4321608040201005
0.4221105527638191
0.09547738693467336